### ISSUE TITLE
Magic Itens don't add Saving Throws bonuses

### ISSUE THREAD

**Issue by bw-mutley** [canismarko/dungeon-sheets#101]
Magic itens like Ring of Protection gives Saving Throw bonuses but dungeon-sheets does not register them. I've fixed it locally by including a st_bonus attribute for items with this property and modifying the Ability class in the same way it is done for AC bonus:

```
saving_throw = modifier
for mitem in entity.magic_items:
    if hasattr(mitem, "st_bonus"):
        saving_throw += mitem.st_bonus
```

**Comment by canismarko** [comment]
Thanks for submitting this issue and including a way to fix it. I fixed the master branch, but haven't updated PyPI yet.

It occurred to me that this is all or nothing: you can't have a magic item that, for example, grants +1 to strength saving throws only. I'm not sure if that's a problem or not. @bw-mutley: are you aware of any magic items that grant bonuses to only some saving throws?

**Comment by bw-mutley** [comment]
Hi there, @canismarko , I am glad to be of help. 

> are you aware of any magic items that grant bonuses to only some saving throws?

I use only Tasha's and DMG in my sessions, and don't recall of any items wich would add only to a specific saving throw. But I'm aware of many magic items which add to DC dificult of spellcasters. Anyway, a more flexible approach to this problem would be to add a _magic_items_bonuses method to Character class which would parse them all.

> ...but haven't updated PyPI yet.

Maybe it is better this way, I have more enhancements in mind. Some of them are mentioned here: [#92 ](https://github.com/canismarko/dungeon-sheets/issues/92#issuecomment-893828411). But also, for a better use of M. Savage template, I've come to some others, one of them is to simplify the display of proficiencies, separating them as armor, weapon and tools. I am planning to work on it next saturday.

**Comment by canismarko** [comment]
> Anyway, a more flexible approach to this problem would be to add a _magic_items_bonuses method to Character class which would parse them all.

I think we'll eventually need some property on the magic item itself that gets called at the right time. Something like Amulet of the Devout from Tasha's seems like it needs even more flexibility than ``_magic_item_bonuses`` could provide.M'kay. I'm going to open a new issue for this.
