### ISSUE TITLE
NameError in `content_registry.ContentRegistry`

### ISSUE THREAD

**Issue by bw-mutley** [canismarko/dungeon-sheets#112]
I've found this after trying to include a "Mace +1" to one of my PC sheet. Follow up the Trace back, it breaks here:

Lines 139 ~ 145 of `content_registry.py` reads:
```
        if bonus > 0:
            if (
                issubclass(attr, weapons.Weapon)
                or issubclass(attr, armor.Shield)
                or issubclass(attr, armor.Armor)
            ):
                attr = attr.improved_version(bonus)
```
But neither `weapons` or `armor` modules ain't imported. 

===EDIT===
As far as I can see, the `if`can be dropped without harm:
if `attr.improved_version` is not defined, it will raise an error, so the user can correct the input.

**Comment by canismarko** [comment]
Yeah it used to be that the content registry added each module, but now each module adds itself so they're not all imported anymore. I think you're right that it can be dropped, the only time that would break is if somehow you had a "+1" item that wasn't a weapon/armor/shield. Maybe you called your homebrew item "amulet of health +2", but that can be guarded against with a call to ``hasattr``:
```
    if bonus > 0 and hasattr(attr, "improved_version"):
        attr = attr.improved_version(bonus)
```

**Comment by bw-mutley** [comment]
Thanks for that!
