### ISSUE TITLE
GM Notes failing with `fancy_decorations=True`

### ISSUE THREAD

**Issue by bw-mutley** [canismarko/dungeon-sheets#113]
Tried to run the following code, using `gm-session-notes.py` avaiable in the `/examples` folder:
```
import dungeonsheets.make_sheets as DnD
DnD.make_sheet("gm-session-notes.py", fancy_decorations=True)
```

Resulted:

```
LatexError: Processing of gm-session-notes.tex failed. See gm-session-notes.log for details.
```

Found the generated .tex file is closing a supertabular environments with `\end{DndTable}`.

Proceding further, found line 210 of `latex.py` to be:
```
       tex = tex.replace(r"\begin{supertabular}[c]", r"\begin{DndTable}")
```
Seens like the string being replaced is wrong, with an extra `"[c]"`. Output ok after removing it. Is there a reason for that extra extra `"[c]"` being there?

P.S.: @canismarko , if you don't want to change for such an small error, I can put this fix in the PR I've sent you some days ago :)

**Comment by canismarko** [comment]
Weird, it actually fails on my computer when I remove the "[c]". I've just pushed a change that replaces both versions, so will you try than let me know if it fixes the problem for you?

**Comment by bw-mutley** [comment]
Ok, I will update my fork and my local dungeonsheets and let you know.

**Comment by bw-mutley** [comment]
Sorry for the (very) late update on this. Current version (updated nov 29) is ok.
