### ISSUE TITLE
Lucky

### ISSUE THREAD

**Issue by kloetzl** [canismarko/dungeon-sheets#136]
There are two features called `lucky`. One is the Halfling's luck the other is the feat with the three luck points. This is an unfortunate name clash. I think it is easier to rename the Halfling's luck as that is not usually added manually to a character.

**Comment by canismarko** [comment]
@kloetzl Thanks for submitting this. I agree it's an issue. A recent PR (https://github.com/canismarko/dungeon-sheets/pull/139) fixed this for a different name clash between features. 

I think your suggestion of renaming the Halfling's luck ("HalflingLuck"?) is a good choice. Are you interesting in preparing a PR?

**Comment by kloetzl** [comment]
Sure, I'll go ahead and create a PR.
