### ISSUE TITLE
disguise self

### ISSUE THREAD

**Issue by johncalab** [canismarko/dungeon-sheets#22]
I seem to bump into a bug when adding the 'Mask of Many Faces' warlock invocation. It times out on me.

Same thing happens if I try and add the disguise self spell directly.

**Comment by geckon** [comment]
This seems to work for me but I kind of remember that there used to be an issue with this spell. Maybe it has been fixed? Could you please try again if it is still an issue? Thanks!

**Comment by canismarko** [comment]
It's been a year and no response on whether this still an issue. I'm going to close this for now. @johncalab if it's still a problem, feel free to reopen.
