### ISSUE TITLE
Inappropriate usage of "is not"

### ISSUE THREAD

**Issue by geckon** [canismarko/dungeon-sheets#43]
There is a couple of cases of inappropriate usage of `is not` operator - e.g.:
```
if my_armor.lower() is not "no armor":
```

**Comment by geckon** [comment]
`!=` makes much more sense in cases like this when one is comparing strings.

**Comment by geckon** [comment]
This may actually fix also issue #25

**Comment by canismarko** [comment]
I agree. Should be testing equality (!=) instead of identity (is not), at least in the example you provided. Feel free to submit a PR.
