### ISSUE TITLE
Maybe a new release?

### ISSUE THREAD

**Issue by geckon** [canismarko/dungeon-sheets#45]
Hi @canismarko, do you by any chance plan to release a new version? Right now `pip install dungeonsheets` will get me version 0.9.4 released in last May and with that I won't get some pretty useful fixes made recently.

I mean, I know how to install and use the version from current master but it would make things easier.

Also, support for Python 3.8 would be awesome declared in the classifiers!

Thanks a lot in advance.

**Comment by canismarko** [comment]
Hi, @geckon.

Good idea. I'd like to get through that back log of PRs first, though. I'm down to 3-4 left so I'll get a new release out once those are done.

**Comment by geckon** [comment]
Great, thanks!

**Comment by canismarko** [comment]
v0.10.0: fcef8ed0b676fb84a34bfe5cac3931a458235244

Also uploaded to pypi.

**Comment by geckon** [comment]
Thanks a lot!
