### ISSUE TITLE
Why is Human race missing?

### ISSUE THREAD

**Issue by geckon** [canismarko/dungeon-sheets#49]
I can only see this: 

![Screenshot from 2020-04-29 23-37-04](https://user-images.githubusercontent.com/120788/80649755-f1736d80-8a72-11ea-9ba7-8be2a0886e16.png)

Why is Human race missing? I mean from the sources I know that Rashemi is the same but what is the reason behind this? Thanks a lot in advance!

**Comment by canismarko** [comment]
Yeah you're right, it should be available even though Rashemi is a human subrace.

Fixed ac921308ffeacceb858560112f92367960088672
