### ISSUE TITLE
Can't run make_sheets.py directly

### ISSUE THREAD

**Issue by geckon** [canismarko/dungeon-sheets#50]
There are relative imports and maybe other issues. I'm willing to fix it. 

@canismarko I have two questions. 
- Are you against me removing relative imports in the whole project if possible? They can be a bit messy sometimes.
- Are you against me moving the two _runnables_ (`create_character.py` and `make_sheets.py`) into the top project directory which is a bit more common alignment?

Thanks for your response!

**Comment by canismarko** [comment]
When you say directly, you mean using ``python make_sheets.py`` or something like that, right?

1. Fine with me. I only ask that all the tests still pass, and that the entry_points still run.
2. I like the idea of not having them in the package directory, but how about making a *run/* directory in the root of the repo and putting them in there? I just noticed that the root directory is getting a little crufty with people's test files and ipython notebooks and I'd like to keep it clean.

**Comment by geckon** [comment]
> When you say directly, you mean using `python make_sheets.py` or something like that, right?
> 

Exactly.

> 1. Fine with me. I only ask that all the tests still pass, and that the entry_points still run.

Sure.

> 2. I like the idea of not having them in the package directory, but how about making a _run/_ directory in the root of the repo and putting them in there? I just noticed that the root directory is getting a little crufty with people's test files and ipython notebooks and I'd like to keep it clean.

I'd say that two executables would be fine in the root dir but I see your point. How about `bin/` though? I know python executables aren't binaries per se but `bin` seems to be a sort of a standard.

**Comment by canismarko** [comment]
Oh yeah, bin/ sounds better. Let's do that.

On Fri, May 01, 2020 at 02:57:12PM -0700, Tomáš Heger wrote:
> > When you say directly, you mean using `python make_sheets.py` or something like that, right?
> > 
> 
> Exactly.
> 
> > 1. Fine with me. I only ask that all the tests still pass, and that the entry_points still run.
> 
> Sure.
> 
> > 2. I like the idea of not having them in the package directory, but how about making a _run/_ directory in the root of the repo and putting them in there? I just noticed that the root directory is getting a little crufty with people's test files and ipython notebooks and I'd like to keep it clean.
> 
> I'd say that two executables would be fine in the root dir but I see your point. How about `bin/` though? I know python executables aren't binaries per se but `bin` seems to be a sort of a standard.
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/canismarko/dungeon-sheets/issues/50#issuecomment-622584179

-- 

This message is signed with Pretty Good Privacy (PGP) key BE1E3158.

http://pool.sks-keyservers.net/pks/lookup?op=get&search=0x457826FCBE1E3158

**Comment by geckon** [comment]
It seems that with setuptools' `entry_points` the scripts need to be a part of a package (and it's probably not a good idea to create a package called `bin`). Maybe I'm missing something but is there another way?

If that's the case we might need to keep it as is, maybe with minimal changes. Unless you'd be willing to switch e.g. to `poetry` which should be able to get us what we want. I use it in a few projects and it's (subjectively) much better than setuptools.

**Comment by canismarko** [comment]
I'm not aware of another way to make entry_points with
setuptools.

I've never needed to run *make_sheets.py* directly so I don't really
have a horse in that race. So far you're the only one that's mentioned
it and you already know where the script lives so I'd prefer to leave
the structure as is and just fix the relative imports, etc.

On Mon, May 04, 2020 at 02:21:49PM -0700, Tomáš Heger wrote:
> It seems that with setuptools' `entry_points` the scripts need to be a part of a package (and it's probably not a good idea to create a package called `bin`). Maybe I'm missing something but is there another way?
> 
> If that's the case we might need to keep it as is, maybe with minimal changes. Unless you'd be willing to switch e.g. to `poetry` which should be able to get us what we want. I use it in a few projects and it's (subjectively) much better than setuptools.
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/canismarko/dungeon-sheets/issues/50#issuecomment-623712867

-- 

This message is signed with Pretty Good Privacy (PGP) key BE1E3158.

http://pool.sks-keyservers.net/pks/lookup?op=get&search=0x457826FCBE1E3158

**Comment by geckon** [comment]
This absolutely makes sense. I added PR for this.

**Comment by canismarko** [comment]
Thanks for fixing all those relative imports (and for putting standard library imports are the top).
