### ISSUE TITLE
Most of the feats are missing

### ISSUE THREAD

**Issue by geckon** [canismarko/dungeon-sheets#51]
I'll go ahead and add them.

**Comment by geckon** [comment]
See PR #52

**Comment by canismarko** [comment]
Thanks @geckon, I'll take at the PR soon.

On Thu, Apr 30, 2020 at 04:01:33PM -0700, Tomáš Heger wrote:
> See PR #52 
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/canismarko/dungeon-sheets/issues/51#issuecomment-622163516

-- 

This message is signed with Pretty Good Privacy (PGP) key BE1E3158.

http://pool.sks-keyservers.net/pks/lookup?op=get&search=0x457826FCBE1E3158
