### ISSUE TITLE
Remove transparency of unprepared spells

### ISSUE THREAD

**Issue by rkubosz** [canismarko/dungeon-sheets#58]
What if we make unprepared spells also solid black as prepared spells?

I play in dnd campaigns as wizard and druid and I found a slight inconvenience. I have a list of known spells and prepared spells. Prepared spells are behaving as I want: spells are printed solid black and marked as prepared on character sheet. 
The problem occurs with unprepared spells. These spells are listed and unmarked on spell card in character sheet but they are printed as grey/transparent in spell descriptions. I get the idea behind this -- it is meant to quickly search for a description of a prepared spell. But in a real life use case it is not working well, at least for me.
Let's say I attend a session with my printed character sheet with spells separated as prepared and unprepared. As session goes, there is at least one long rest, meaning that I change my prepared spells. Now one or some spells that I have prepared have a transparent and quite unreadable description.
IMO the best use of spells in character sheet is to make them all unprepared, but then they all print in unreadable gray. I can mark prepared spells on a printed sheet with a pencil and change them during session.

What we can make:
- change the transparency/gray color to solid black for unprepared spells (permanent solution) or 
- add an option in character.py file for user to choose the color of unprepared spells

ps for a moment I thought that it could be a simplified spell list without separating it to prepared and unprepared, but for example my circle of spores druid has some spells that are always prepared, so imo we should keep the separation of prepared and unprepared spells

**Comment by canismarko** [comment]
Yeah I can see that being annoying.

I'd prefer something like your second idea of having it be an option in the character python file, though I'd also rather limit the .py files to descriptions of the character itself, not preferences for how the sheets are rendered.

How about adding a command line option to *make_sheets.py* that changes the color. Maybe ``--unprepared-spell-color=grey`` and ``-u grey``? That way people can change the color to suite their preference. The downside here is that you have to remember to add that flag every time you run makesheets, which then creates a need for a dunegonsheets.rc file or something like that.

Would that work for your use case?

**Comment by geckon** [comment]
My 2 cents: 

I agree that having spells greyed out makes them unreadable sometimes. I personally would prefer to have all spells in black and track those that are prepared separately (e.g. marking them myself with a pencil). Having unprepared spells readable is also useful for deciding which spells I want to prepare.

An option would be ok, although I'd probably not go for `-u` since that is too unclear what `u` means but maybe that's just me. A configuration file might be nice, especially if there is more choices like that in the future. And I definitely agree that it's better to keep things like this somewhere else than in the character definition file.

**Comment by canismarko** [comment]
Well it would be ``--unprepared-spell-color=grey`` with a short ``-u`` option as well.

Maybe it's better to just make them all the same color for now, and then find a way to indicate which, if any, are prepared, with an asterisk or something. That way, the use of prepared spells is optional.

I'm still working on this open PR (https://github.com/canismarko/dungeon-sheets/pull/18) to use a D&D themed LaTeX template for spell lists, so there might be a more obvious way to indicate which spells are prepared. I've accepted the PR for this change and we can think about the way to bring *prepared_spells* back in later.
