### ISSUE TITLE
Remove cruft from the root repository directory

### ISSUE THREAD

**Issue by canismarko** [canismarko/dungeon-sheets#63]
People have added a bunch of stray files that aren't really essential for the project. Some of them should be moved to the *examples/* folder, while other can maybe be removed.

**Comment by canismarko** [comment]
I'd also like to get rid of the example PDFs (keep the source .py files) since they're generated files and not source files.

**Comment by geckon** [comment]
Oh yes please. Do you want me to do it?

**Comment by canismarko** [comment]
No thanks. I'd like to do it for some cleaning therapy. =)

On Fri, May 01, 2020 at 02:51:14PM -0700, Tomáš Heger wrote:
> Oh yes please. Do you want me to do it?
> 
> -- 
> You are receiving this because you were assigned.
> Reply to this email directly or view it on GitHub:
> https://github.com/canismarko/dungeon-sheets/issues/63#issuecomment-622582533

-- 

This message is signed with Pretty Good Privacy (PGP) key BE1E3158.

http://pool.sks-keyservers.net/pks/lookup?op=get&search=0x457826FCBE1E3158

**Comment by canismarko** [comment]
22c3e4dbeb1928645430c85ed99edcc25de7d0bd
