### ISSUE TITLE
Cannot include the dndbook class

### ISSUE THREAD

**Issue by DanRoscigno** [canismarko/dungeon-sheets#73]
I tried adding `-F` on the commandline to include the dndbook class (as documented in the README) and got an error telling me that there is no such arg.
`If you have to excellent dndbook LaTeX template, consider using the -F option to include this template for rendering spellbooks, druid wild forms and features pages`

I am using release 0.10.1

Thanks so much for dungeon-sheets, it is really helping me learn DnD.

**Comment by canismarko** [comment]
You're welcome, glad you find it useful.

I'm a little miffed about this error. I'm using the argparse package from standard lib, so recognizing options should be pretty robust. Would you mind pasting the output from ``makesheets -h``?

**Comment by DanRoscigno** [comment]
I think that the version in master was not included in the May 4th release.  I compared the code installed with master and the processing of `-F` is not there.  I also downloaded the release zip and looked at the code, it is not in the zip file.

Here is the -h output:
```
usage: makesheets [-h] [--editable] [--debug] [filename]

Prepare Dungeons and Dragons character sheets as PDFs

positional arguments:
  filename        Python file with character definition

optional arguments:
  -h, --help      show this help message and exit
  --editable, -e  Keep the PDF fields in place once processed.
  --debug, -d     Provide verbose logging for debugging purposes.
```

**Comment by DanRoscigno** [comment]
which makes sense, the latest release was on 4 May, and you merged the commit on 6 May:

![image](https://user-images.githubusercontent.com/25182304/84542219-fb6dca80-acc6-11ea-8ed7-fc8ede95bd62.png)

I will try to run master.

**Comment by DanRoscigno** [comment]
Sorry for the drama!  I installed master and all is well!
```
droscigno@Dans-Mac-mini Downloads % makesheets -h
usage: makesheets [-h] [--editable] [--fancy-decorations] [--debug] [filename]

Prepare Dungeons and Dragons character sheets as PDFs

positional arguments:
  filename              Python file with character definition

optional arguments:
  -h, --help            show this help message and exit
  --editable, -e        Keep the PDF fields in place once processed.
  --fancy-decorations, -F
                        Render extra pages using fancy decorations
                        (experimental, requires
                        https://github.com/rpgtex/DND-5e-LaTeX-Template)
  --debug, -d           Provide verbose logging for debugging purposes.
droscigno@Dans-Mac-mini Downloads % cd
droscigno@Dans-Mac-mini ~ % makesheets -F darvas-level3.py 
Processing darvas-level3...
darvas-level3 done
```

![image](https://user-images.githubusercontent.com/25182304/84542750-168d0a00-acc8-11ea-91ac-a13c122b4fdf.png)
