### ISSUE TITLE
`makesheets` on examples failing

### ISSUE THREAD

**Issue by jakewilliami** [canismarko/dungeon-sheets#77]
```
 $ git clone https://github.com/bacook17/dungeon-sheets
Cloning into 'dungeon-sheets'...
remote: Enumerating objects: 1273, done.
remote: Total 1273 (delta 0), reused 0 (delta 0), pack-reused 1273
Receiving objects: 100% (1273/1273), 8.50 MiB | 1.50 MiB/s, done.
Resolving deltas: 100% (943/943), done.

 $ cd dungeon-sheets/examples/

 $ ls
barbarian1.pdf  bard2.py        druid2.pdf      makefile        multiclass1.py  ranger2.pdf     rogue2.py       warlock2.pdf
barbarian1.py   cleric1.pdf     druid2.py       monk1.pdf       multiclass2.pdf ranger2.py      sorceror1.pdf   warlock2.py
barbarian2.pdf  cleric1.py      druid3.py       monk1.py        multiclass2.py  ranger3.pdf     sorceror1.py    wizard1.pdf
barbarian2.py   cleric2.pdf     fighter1.pdf    monk2.pdf       paladin1.py     ranger3.py      sorceror2.pdf   wizard1.py
bard1.pdf       cleric2.py      fighter1.py     monk2.py        paladin2.py     rogue1.pdf      sorceror2.py    wizard2.pdf
bard1.py        druid1.pdf      fighter2.pdf    multiclass      ranger1.pdf     rogue1.py       warlock1.pdf    wizard2.py
bard2.pdf       druid1.py       fighter2.py     multiclass1.pdf ranger1.py      rogue2.pdf      warlock1.py

 $ makesheets
Processing rogue2...done
Processing barbarian1...done
Processing fighter2...done
Processing warlock1...done
Processing wizard2...done
Processing sorceror1...done
Processing paladin1...done
Processing ranger2...done
Processing monk1...done
Processing ranger3...done
Processing druid1...done
Processing multiclass1...failed
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/bin/makesheets", line 8, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/dungeonsheets/make_sheets.py", line 554, in main
    make_sheet(character_file=filename, flatten=(not args.editable), debug=args.debug)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/dungeonsheets/make_sheets.py", line 453, in make_sheet
    character = _char.Character.load(character_file)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/dungeonsheets/character.py", line 722, in load
    char = Character(**char_props)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/dungeonsheets/character.py", line 159, in __init__
    self.set_attrs(**attrs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/dungeonsheets/character.py", line 474, in set_attrs
    self.wear_armor(val)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/dungeonsheets/character.py", line 610, in wear_armor
    NewArmor = findattr(armor, new_armor)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/dungeonsheets/stats.py", line 38, in findattr
    raise AttributeError(f'{obj} has no attribute {name}')
AttributeError: <module 'dungeonsheets.armor' from '/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/dungeonsheets/armor.py'> has no attribute studded armor
```

**Comment by canismarko** [comment]
I can't seem to reproduce this behavior. Mind checking a couple of things for me?

1) It looks like you're pulling from bacook17's fork. Mind pulling from my repo and checking again?

2) Running ``makesheets`` from inside the examples directory shouldn't be possible without first installing the package somehow. Make sure to run ``pip install -e dungeon-sheets/`` after the ``git clone ...`` command.

Let me know if either of those fixes the issue. If not, I'll have to take a closer look.

**Comment by jakewilliami** [comment]
Huh, I didn't realise I wasn't pulling from your repo—sorry about that!  The reason I was pulling from bacook17's clone was because the link in the README (line 66) to the examples directory leads to their clone.  Trying this with your repo, here is what I get:
```
 $ git clone https://github.com/canismarko/dungeon-sheets/
Cloning into 'dungeon-sheets'...
remote: Enumerating objects: 133, done.
remote: Counting objects: 100% (133/133), done.
remote: Compressing objects: 100% (93/93), done.
remote: Total 1959 (delta 83), reused 74 (delta 40), pack-reused 1826
Receiving objects: 100% (1959/1959), 13.52 MiB | 4.53 MiB/s, done.
Resolving deltas: 100% (1465/1465), done.

 $ cd dungeon-sheets/examples/

 $ makesheets
Processing rogue2...done
Processing barbarian1...done
Processing fighter2...done
Processing warlock1...done
Processing wizard2...done
Processing sorceror1...done
Processing paladin1...done
Processing ranger2...done
Processing monk1...done
Processing ranger3...done
Processing druid1...done
Processing multiclass1...done
Processing cleric2...done
Processing bard1...done
Processing monk2...done
Processing druid2...done
Processing multiclass2...done
Processing cleric1...done
Processing bard2...done
Processing sorceror2...done
Processing wizard1...done
Processing paladin2...done
Processing ranger1...done
Processing druid3...done
Processing warlock2...done
Processing rogue1...done
Processing barbarian2...done
Processing artificer1...failed
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/dungeonsheets/character.py", line 187, in add_class
    cls = getattr(classes, cls)
AttributeError: module 'dungeonsheets.classes' has no attribute 'Artificer'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/bin/makesheets", line 8, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/dungeonsheets/make_sheets.py", line 554, in main
    make_sheet(character_file=filename, flatten=(not args.editable), debug=args.debug)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/dungeonsheets/make_sheets.py", line 453, in make_sheet
    character = _char.Character.load(character_file)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/dungeonsheets/character.py", line 722, in load
    char = Character(**char_props)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/dungeonsheets/character.py", line 154, in __init__
    feature_choices=attrs.get('feature_choices', []))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/dungeonsheets/character.py", line 220, in add_classes
    **params)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/dungeonsheets/character.py", line 190, in add_class
    'class was not recognized from classes.py: {:s}'.format(cls))
AttributeError: class was not recognized from classes.py: Artificer
```

I have already run `pip install dungeonsheets` as per the instructions for the [character sheet setup](https://github.com/michaelplews/DnD-character-sheets/blob/master/README.md), but running your suggested `pip install` command seems to work:
```
$ pip install -e dungeon-sheets/
Obtaining file:///Users/jakeireland/git-workspace/dungeon-sheets
Requirement already satisfied: fdfgen in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from dungeonsheets==0.10.1) (0.16.1)
Requirement already satisfied: npyscreen in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from dungeonsheets==0.10.1) (4.10.5)
Requirement already satisfied: jinja2 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from dungeonsheets==0.10.1) (2.11.2)
Requirement already satisfied: pdfrw in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from dungeonsheets==0.10.1) (0.4)
Requirement already satisfied: MarkupSafe>=0.23 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from jinja2->dungeonsheets==0.10.1) (1.1.1)
Installing collected packages: dungeonsheets
  Attempting uninstall: dungeonsheets
    Found existing installation: dungeonsheets 0.10.1
    Uninstalling dungeonsheets-0.10.1:
      Successfully uninstalled dungeonsheets-0.10.1
  Running setup.py develop for dungeonsheets
Successfully installed dungeonsheets

 $ cd dungeon-sheets/examples/

 $ makesheets
Processing rogue2...
Processing fighter2...
Processing wizard2...
Processing paladin1...
rogue2 done
Processing barbarian1...
wizard2 done
Processing sorceror1...
fighter2 done
Processing warlock1...
barbarian1 done
Processing monk1...
paladin1 done
Processing ranger2...
monk1 done
Processing ranger3...
sorceror1 done
Processing druid1...
ranger2 done
Processing cleric2...
warlock1 done
Processing monk2...
ranger3 done
Processing multiclass2...
monk2 done
Processing druid2...
cleric2 done
Processing bard1...
multiclass2 done
Processing cleric1...
druid1 done
Processing multiclass1...
druid2 done
Processing bard2...
cleric1 done
Processing wizard1...
bard1 done
Processing ranger1...
multiclass1 done
Processing warlock2...
bard2 done
Processing sorceror2...
ranger1 done
Processing druid3...
wizard1 done
Processing paladin2...
warlock2 done
Processing rogue1...
rogue1 done
Processing barbarian2...
sorceror2 done
Processing fighter1...
paladin2 done
barbarian2 done
Processing artificer1...
druid3 done
fighter1 done
artificer1 done
```

Thank you so much for your help on this.  Do you know why `pip install dungeonsheets` does not work?

**Comment by canismarko** [comment]
Ah, gotcha. I fixed the wrong link in the README. ``pip install
dungeonsheets`` pulls from the PyPI, so probably that was out of
date. I just uploaded a newer version (v0.10.2) to PyPI, so ``pip
install --upgrade dungeonsheets`` will hopefully get everything up to
date.

On Fri, Jul 10, 2020 at 06:21:01AM -0700, Jake Ireland wrote:
> Huh, I didn't realise I wasn't pulling from your repo—sorry about that!  The reason I was pulling from bacook17's clone was because the link in the README (line 66) to the examples directory leads to their clone.  Trying this with your repo, here is what I get:
> ```
>  $ git clone https://github.com/canismarko/dungeon-sheets/
> Cloning into 'dungeon-sheets'...
> remote: Enumerating objects: 133, done.
> remote: Counting objects: 100% (133/133), done.
> remote: Compressing objects: 100% (93/93), done.
> remote: Total 1959 (delta 83), reused 74 (delta 40), pack-reused 1826
> Receiving objects: 100% (1959/1959), 13.52 MiB | 4.53 MiB/s, done.
> Resolving deltas: 100% (1465/1465), done.
> 
>  $ cd dungeon-sheets/examples/
> 
>  $ makesheets
> Processing rogue2...done
> Processing barbarian1...done
> Processing fighter2...done
> Processing warlock1...done
> Processing wizard2...done
> Processing sorceror1...done
> Processing paladin1...done
> Processing ranger2...done
> Processing monk1...done
> Processing ranger3...done
> Processing druid1...done
> Processing multiclass1...done
> Processing cleric2...done
> Processing bard1...done
> Processing monk2...done
> Processing druid2...done
> Processing multiclass2...done
> Processing cleric1...done
> Processing bard2...done
> Processing sorceror2...done
> Processing wizard1...done
> Processing paladin2...done
> Processing ranger1...done
> Processing druid3...done
> Processing warlock2...done
> Processing rogue1...done
> Processing barbarian2...done
> Processing artificer1...failed
> Traceback (most recent call last):
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/dungeonsheets/character.py", line 187, in add_class
>     cls = getattr(classes, cls)
> AttributeError: module 'dungeonsheets.classes' has no attribute 'Artificer'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/Library/Frameworks/Python.framework/Versions/3.7/bin/makesheets", line 8, in <module>
>     sys.exit(main())
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/dungeonsheets/make_sheets.py", line 554, in main
>     make_sheet(character_file=filename, flatten=(not args.editable), debug=args.debug)
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/dungeonsheets/make_sheets.py", line 453, in make_sheet
>     character = _char.Character.load(character_file)
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/dungeonsheets/character.py", line 722, in load
>     char = Character(**char_props)
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/dungeonsheets/character.py", line 154, in __init__
>     feature_choices=attrs.get('feature_choices', []))
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/dungeonsheets/character.py", line 220, in add_classes
>     **params)
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/dungeonsheets/character.py", line 190, in add_class
>     'class was not recognized from classes.py: {:s}'.format(cls))
> AttributeError: class was not recognized from classes.py: Artificer
> ```
> 
> I have already run `pip install dungeonsheets` as per the instructions for the [character sheet setup](https://github.com/michaelplews/DnD-character-sheets/blob/master/README.md), but running your suggested `pip install` command seems to work:
> ```
> $ pip install -e dungeon-sheets/
> Obtaining file:///Users/jakeireland/git-workspace/dungeon-sheets
> Requirement already satisfied: fdfgen in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from dungeonsheets==0.10.1) (0.16.1)
> Requirement already satisfied: npyscreen in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from dungeonsheets==0.10.1) (4.10.5)
> Requirement already satisfied: jinja2 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from dungeonsheets==0.10.1) (2.11.2)
> Requirement already satisfied: pdfrw in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from dungeonsheets==0.10.1) (0.4)
> Requirement already satisfied: MarkupSafe>=0.23 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from jinja2->dungeonsheets==0.10.1) (1.1.1)
> Installing collected packages: dungeonsheets
>   Attempting uninstall: dungeonsheets
>     Found existing installation: dungeonsheets 0.10.1
>     Uninstalling dungeonsheets-0.10.1:
>       Successfully uninstalled dungeonsheets-0.10.1
>   Running setup.py develop for dungeonsheets
> Successfully installed dungeonsheets
> 
>  $ cd dungeon-sheets/examples/
> 
>  $ makesheets
> Processing rogue2...
> Processing fighter2...
> Processing wizard2...
> Processing paladin1...
> rogue2 done
> Processing barbarian1...
> wizard2 done
> Processing sorceror1...
> fighter2 done
> Processing warlock1...
> barbarian1 done
> Processing monk1...
> paladin1 done
> Processing ranger2...
> monk1 done
> Processing ranger3...
> sorceror1 done
> Processing druid1...
> ranger2 done
> Processing cleric2...
> warlock1 done
> Processing monk2...
> ranger3 done
> Processing multiclass2...
> monk2 done
> Processing druid2...
> cleric2 done
> Processing bard1...
> multiclass2 done
> Processing cleric1...
> druid1 done
> Processing multiclass1...
> druid2 done
> Processing bard2...
> cleric1 done
> Processing wizard1...
> bard1 done
> Processing ranger1...
> multiclass1 done
> Processing warlock2...
> bard2 done
> Processing sorceror2...
> ranger1 done
> Processing druid3...
> wizard1 done
> Processing paladin2...
> warlock2 done
> Processing rogue1...
> rogue1 done
> Processing barbarian2...
> sorceror2 done
> Processing fighter1...
> paladin2 done
> barbarian2 done
> Processing artificer1...
> druid3 done
> fighter1 done
> artificer1 done
> ```
> 
> Thank you so much for your help on this.  Do you know why `pip install dungeonsheets` does not work?
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/canismarko/dungeon-sheets/issues/77#issuecomment-656673492

-- 

This message is signed with Pretty Good Privacy (PGP) key BE1E3158.

http://pool.sks-keyservers.net/pks/lookup?op=get&search=0x457826FCBE1E3158
