### ISSUE TITLE
Ranger class is mentioned as a source of Figter's styles

### ISSUE THREAD

**Issue by kompoth** [canismarko/dungeon-sheets#88]
Despite FighterFightingStyle defines `source = 'Fighter'`, in the output pdf file 'Defense' Fighter's style is sourced from Ranger's class. Not sure if the 'source' field was intended this way.

**Comment by canismarko** [comment]
Not sure, but thanks for letting me know. I'll take a look when I have some free time.

**Comment by bw-mutley** [comment]
It seens to be fixed. Tested with tex template and pdftk, could not reproduce it.

**Comment by canismarko** [comment]
Sounds good. I'm going to close this. @kompoth: feel free to re-open if you have steps to reproduce this.
