### ISSUE TITLE
Homebrew: Cannot specify a weapon subclass

### ISSUE THREAD

**Issue by DanRoscigno** [canismarko/dungeon-sheets#99]
I am trying to add a new weapon, and I would like to be able to mark it as a SimpleWeapon as my char is proficient with SimpleWeapons.  I tried the below, but it fails, and I cannot figure out how to include SimpleWeapon.  Is there a way to specify that a weapon is a simpleweapon?

```
class BlueSting(mechanics.SimpleWeapon):
    name = "Blue Sting"
    cost = "1000 gp"
    base_damage = "1d6"
    attack_bonus = 1
    damage_bonus = 1
    damage_type = "p"
    weight = 1
    ability = "dexterity"
```

**Comment by DanRoscigno** [comment]
I was able to add the proficiency:
```
 weapon_proficiencies = (BlueSting, MagicSpear)
```

**Comment by canismarko** [comment]
Adding it to the proficiences is a good workaround. For future convenience, I added SimpleWeapon and a few others to the mechanics module.
